// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfweoayfuotqpspdeaes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmd2VvYXlmdW90cXBzcGRlYWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODA0MzUsImV4cCI6MjA1NzM1NjQzNX0.6TOzHSivq2O2-HhgPDiHlXSZV5u-KfVfvhdG8-QTze0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);